[package]
name = "my_home_hue"
version = "0.1.0"
authors = ["ayase <paper.airplane01@gmail.com>"]
edition = "2018"

[dependencies]
failure="*"
serde="*"
serde_derive="*"
serde_json="*"
toml="*"
reqwest="*"